name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y libgpgme-dev
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.12'
      - run: go test -v ./...

  ubuntu-ppe64le:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ppc64le
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -y libgpgme-dev golang
          run: |
            go test -v ./...

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install gpgme gnupg@1.4
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.12'
      - run: go test -v ./...
